<a href="https://colab.research.google.com/github/Subhasree5/Ml-Workshop-/blob/main/Assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.

In [2]:
import numpy as np
a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
addition = np.add(a,b)
subtraction = np.subtract(a,b)
multiplication = np.multiply(a,b)
divide=np.divide(a,b)
print(addition, subtraction, multiplication, divide)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


Write a script to compute the mean and standard deviation of a NumPy array.

In [3]:
a = np.array([1, 2, 3, 4, 5])

mean = np.mean(a)
sd = np.std(a)

print("Mean:", mean)
print("Standard Deviation:", sd)

Mean: 3.0
Standard Deviation: 1.4142135623730951


Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [4]:
a=np.arange(10,51,5)
print (a)

[10 15 20 25 30 35 40 45 50]


Reshape the array into a 2x4 matrix

In [6]:
a =np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_array = a.reshape(2, 4)
print("Reshaped Array:", reshaped_array)

Reshaped Array: [[1 2 3 4]
 [5 6 7 8]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = a[1:3, 0:2]
a[a > 4] = 0
print("last two rows and first two columns:")
print(sub_matrix)
print("replaced array:")
print(a)

last two rows and first two columns:
[[4 0]
 [0 0]]
replaced array:
[[1 2 3]
 [4 0 0]
 [0 0 0]]


Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [8]:
arr = np.random.rand(4, 4)
column_means = np.mean(arr, axis=0)
max_value = np.max(arr)
sum_of_elements = np.sum(arr)
print("Mean of each column:", column_means)
print("Maximum value:", max_value)
print("Sum of all elements:", sum_of_elements)

Mean of each column: [0.47272774 0.55913614 0.59464481 0.35523012]
Maximum value: 0.9915127301761522
Sum of all elements: 7.926955274110938


Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [10]:
arr = np.array([1, 2, 3, 4])
result=(arr+10)*2
print(result)

[22 24 26 28]


Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [11]:
arr = np.random.randint(1, 101, (3, 4, 5))
print("Original 3D Array:\n", arr)
second_layer = arr[1]
print("\n2D Array from First Dimension", second_layer)
b= arr[:, :2, -3:]
print("\nFirst Two Rows and Last Three Columns from Each Layer:\n",b)
arr[arr % 3 == 0] = -1
print("\nArray After Replacing :\n", arr)

Original 3D Array:
 [[[68 33 58 90 76]
  [33 82 33 37 27]
  [10 23 18  6 86]
  [64 80  9 22 46]]

 [[99 33 86 59 13]
  [62 31 48 24 88]
  [27 46 43 31 25]
  [28 21 32 25 92]]

 [[ 5 98 86 39 19]
  [27 32 31 91 76]
  [98  8  5 37 93]
  [95  2 36 96  2]]]

2D Array from First Dimension [[99 33 86 59 13]
 [62 31 48 24 88]
 [27 46 43 31 25]
 [28 21 32 25 92]]

First Two Rows and Last Three Columns from Each Layer:
 [[[58 90 76]
  [33 37 27]]

 [[86 59 13]
  [48 24 88]]

 [[86 39 19]
  [31 91 76]]]

Array After Replacing :
 [[[68 -1 58 -1 76]
  [-1 82 -1 37 -1]
  [10 23 -1 -1 86]
  [64 80 -1 22 46]]

 [[-1 -1 86 59 13]
  [62 31 -1 -1 88]
  [-1 46 43 31 25]
  [28 -1 32 25 92]]

 [[ 5 98 86 -1 19]
  [-1 32 31 91 76]
  [98  8  5 37 -1]
  [95  2 -1 -1  2]]]
