<a href="https://colab.research.google.com/github/Subhasree5/Ml-Workshop-/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Perform arithmetic operations on NumPy arrays.
import numpy as np
a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
add=np.add(a,b)
sub=np.subtract(a,b)
mul=np.multiply(a,b)
div=np.divide(a,b)
print(add,sub,mul,div)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [ ]:
#2.Write a script to compute the mean and standard deviation of a NumPy array.
a=np.array([1,2,3,4,5])
print(np.mean(a),np.std(a))

3.0 1.4142135623730951


In [ ]:
#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [ ]:
#4. Reshape the array into a 2x4 matrix.
a=np.array(([10,20,30],[1,2,3]))
print(a.reshape(3,2))

[[10 20]
 [30  1]
 [ 2  3]]


In [ ]:
#5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#Extract the sub-matrix containing the last two rows and first two columns.
sub=arr[1:, :2]
print(sub)
#Replace all elements greater than 4 with 0.
arr[arr>4]=0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


In [ ]:
#Perform element-wise addition, multiplication, and division.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add=a+b
sub=a-b
mul=a*b
div=a/b
print(add,sub,mul,div)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [ ]:
#7. Create a random NumPy array of size (4, 4):
a=np.random.rand(4,4)
print(a)
#Mean of each column.
mean=np.mean(a,axis=0)
#Maximum value of the entire array.
max=np.max(a)
#Sum of all elements.
sum=np.sum(a)
print (mean,max,sum)

[[0.48047289 0.44085311 0.46228326 0.2883809 ]
 [0.89775252 0.27753908 0.97944452 0.05455268]
 [0.7977551  0.20732953 0.0650736  0.16748971]
 [0.605873   0.09943065 0.31256009 0.37834856]]
[0.69546338 0.25628809 0.45484037 0.22219296] 0.9794445214513425 6.515139195057623


In [ ]:
#add 10 to each element and multiply the result by 2.
arr = np.array([1, 2, 3, 4])
result=(arr+10)*2
print (result)

[22 24 26 28]


In [ ]:
#10. Work with broadcasting and advanced operations in NumPy.
import numpy as np
arr = np.random.randint(1, 21, size=(3, 3))
# Subtract the mean of each row from its respective elements
row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means
print("Normalized array:", normalized_arr)

# Create a new array by squaring all the elements
squared_arr = arr ** 2
print("Squared array:", squared_arr)

# Find the indices of the top 3 maximum values
flat_arr = arr.flatten()
top_3_indices = np.argpartition(flat_arr, -3)[-3:]
print("Indices of top 3 maximum values:", top_3_indices)

Normalized array: [[  1.   4.  -5.]
 [  2. -10.   8.]
 [  6.   0.  -6.]]
Squared array: [[121 196  25]
 [169   1 361]
 [196  64   4]]
Indices of top 3 maximum values: [6 1 5]
